kind = "web"
previewPath = "/"
title = "ExamManagerOS"
version = "1.0.0"
id = "artifacts/exammanageros"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25927

[services.development]
run = "pnpm --filter @workspace/exammanageros run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/exammanageros", "run", "build" ]
publicDir = "artifacts/exammanageros/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25927"
BASE_PATH = "/"
