import {
  clientsTable,
  candidatesTable,
  examsTable,
  examRequirementsTable,
  examProvidersTable,
  relatedApplicationsTable,
  transcriptRecordsTable,
  studyPrepRecordsTable,
  tasksTable,
  escalationsTable,
  clientUpdateDraftsTable,
} from "@workspace/db";

export function rowToClient(r: typeof clientsTable.$inferSelect) {
  return { id: r.id, name: r.name, entityName: r.entityName, accountManager: r.accountManager, contactName: r.contactName, contactEmail: r.contactEmail, riskLevel: r.riskLevel, createdAt: r.createdAt, updatedAt: r.updatedAt };
}
export function clientToRow(c: Record<string, unknown>) {
  return { id: String(c.id), name: String(c.name), entityName: String(c.entityName), accountManager: String(c.accountManager), contactName: String(c.contactName), contactEmail: String(c.contactEmail), riskLevel: String(c.riskLevel), createdAt: String(c.createdAt), updatedAt: String(c.updatedAt) };
}
export function rowToCandidate(r: typeof candidatesTable.$inferSelect) {
  return { id: r.id, clientId: r.clientId, fullName: r.fullName, email: r.email, phone: r.phone, role: r.role, qualifierType: r.qualifierType, statesAssociated: r.statesAssociated, notes: r.notes, createdAt: r.createdAt, updatedAt: r.updatedAt };
}
export function candidateToRow(c: Record<string, unknown>) {
  return { id: String(c.id), clientId: String(c.clientId), fullName: String(c.fullName), email: String(c.email), phone: String(c.phone), role: String(c.role), qualifierType: String(c.qualifierType), statesAssociated: c.statesAssociated as string[], notes: String(c.notes), createdAt: String(c.createdAt), updatedAt: String(c.updatedAt) };
}
export function rowToExam(r: typeof examsTable.$inferSelect) {
  return { id: r.id, clientId: r.clientId, candidateId: r.candidateId, relatedApplicationIds: r.relatedApplicationIds, examName: r.examName, examType: r.examType, jurisdiction: r.jurisdiction, state: r.state, boardAgency: r.boardAgency, provider: r.provider, status: r.status, eligibilityStatus: r.eligibilityStatus, studyStatus: r.studyStatus, registrationStatus: r.registrationStatus, scheduledDate: r.scheduledDate, scheduledTime: r.scheduledTime, testingLocation: r.testingLocation, completedDate: r.completedDate, resultStatus: r.resultStatus, transcriptStatus: r.transcriptStatus, transcriptRequired: r.transcriptRequired, applicationBlocked: r.applicationBlocked, owner: r.owner, reviewer: r.reviewer, nextAction: r.nextAction, dueDate: r.dueDate, riskLevel: r.riskLevel, blocker: r.blocker, clientVisibleStatus: r.clientVisibleStatus, internalNotes: r.internalNotes, createdAt: r.createdAt, updatedAt: r.updatedAt };
}
export function examToRow(e: Record<string, unknown>) {
  return { id: String(e.id), clientId: String(e.clientId), candidateId: String(e.candidateId), relatedApplicationIds: e.relatedApplicationIds as string[], examName: String(e.examName), examType: String(e.examType), jurisdiction: String(e.jurisdiction), state: String(e.state), boardAgency: String(e.boardAgency), provider: String(e.provider), status: String(e.status), eligibilityStatus: String(e.eligibilityStatus), studyStatus: String(e.studyStatus), registrationStatus: String(e.registrationStatus), scheduledDate: e.scheduledDate as string | null, scheduledTime: e.scheduledTime as string | null, testingLocation: e.testingLocation as string | null, completedDate: e.completedDate as string | null, resultStatus: String(e.resultStatus), transcriptStatus: String(e.transcriptStatus), transcriptRequired: Boolean(e.transcriptRequired), applicationBlocked: Boolean(e.applicationBlocked), owner: String(e.owner), reviewer: String(e.reviewer), nextAction: String(e.nextAction), dueDate: e.dueDate as string | null, riskLevel: String(e.riskLevel), blocker: String(e.blocker), clientVisibleStatus: String(e.clientVisibleStatus), internalNotes: String(e.internalNotes), createdAt: String(e.createdAt), updatedAt: String(e.updatedAt) };
}
export function rowToRequirement(r: typeof examRequirementsTable.$inferSelect) { return { id: r.id, examId: r.examId, requirementName: r.requirementName, requirementType: r.requirementType, required: r.required, status: r.status, source: r.source, notes: r.notes }; }
export function requirementToRow(r: Record<string, unknown>) { return { id: String(r.id), examId: String(r.examId), requirementName: String(r.requirementName), requirementType: String(r.requirementType), required: Boolean(r.required), status: String(r.status), source: String(r.source), notes: String(r.notes) }; }
export function rowToProvider(r: typeof examProvidersTable.$inferSelect) { return { id: r.id, providerName: r.providerName, website: r.website, schedulingMethod: r.schedulingMethod, transcriptMethod: r.transcriptMethod, supportNotes: r.supportNotes }; }
export function providerToRow(p: Record<string, unknown>) { return { id: String(p.id), providerName: String(p.providerName), website: String(p.website), schedulingMethod: String(p.schedulingMethod), transcriptMethod: String(p.transcriptMethod), supportNotes: String(p.supportNotes) }; }
export function rowToApplication(r: typeof relatedApplicationsTable.$inferSelect) { return { id: r.id, clientId: r.clientId, examId: r.examId, applicationName: r.applicationName, applicationNumber: r.applicationNumber, state: r.state, licenseClassification: r.licenseClassification, applicationStatus: r.applicationStatus, blockedByExam: r.blockedByExam, blockedByTranscript: r.blockedByTranscript, dependencyType: r.dependencyType, whatCanProceedAfterPass: r.whatCanProceedAfterPass, whatCanProceedAfterTranscript: r.whatCanProceedAfterTranscript, owner: r.owner, nextStepAfterUnblocked: r.nextStepAfterUnblocked }; }
export function applicationToRow(a: Record<string, unknown>) { return { id: String(a.id), clientId: String(a.clientId), examId: String(a.examId), applicationName: String(a.applicationName), applicationNumber: String(a.applicationNumber), state: String(a.state), licenseClassification: String(a.licenseClassification), applicationStatus: String(a.applicationStatus), blockedByExam: Boolean(a.blockedByExam), blockedByTranscript: Boolean(a.blockedByTranscript), dependencyType: String(a.dependencyType), whatCanProceedAfterPass: String(a.whatCanProceedAfterPass), whatCanProceedAfterTranscript: String(a.whatCanProceedAfterTranscript), owner: String(a.owner), nextStepAfterUnblocked: String(a.nextStepAfterUnblocked) }; }
export function rowToTranscript(r: typeof transcriptRecordsTable.$inferSelect) { return { id: r.id, examId: r.examId, candidateId: r.candidateId, transcriptRequired: r.transcriptRequired, transcriptStatus: r.transcriptStatus, orderedDate: r.orderedDate, provider: r.provider, deliveryMethod: r.deliveryMethod, sentToBoard: r.sentToBoard, sentToState: r.sentToState, receivedByBoard: r.receivedByBoard, receivedDate: r.receivedDate, confirmationNumber: r.confirmationNumber, followUpDueDate: r.followUpDueDate, issueNotes: r.issueNotes }; }
export function transcriptToRow(t: Record<string, unknown>) { return { id: String(t.id), examId: String(t.examId), candidateId: String(t.candidateId), transcriptRequired: Boolean(t.transcriptRequired), transcriptStatus: String(t.transcriptStatus), orderedDate: t.orderedDate as string | null, provider: String(t.provider), deliveryMethod: String(t.deliveryMethod), sentToBoard: Boolean(t.sentToBoard), sentToState: Boolean(t.sentToState), receivedByBoard: Boolean(t.receivedByBoard), receivedDate: t.receivedDate as string | null, confirmationNumber: String(t.confirmationNumber), followUpDueDate: t.followUpDueDate as string | null, issueNotes: String(t.issueNotes) }; }
export function rowToStudyPrep(r: typeof studyPrepRecordsTable.$inferSelect) { return { id: r.id, examId: r.examId, studyMaterialsRequired: r.studyMaterialsRequired, studyMaterialsOrdered: r.studyMaterialsOrdered, studyMaterialsReceived: r.studyMaterialsReceived, studyProvider: r.studyProvider, prepCourseStatus: r.prepCourseStatus, candidateReadinessConfirmed: r.candidateReadinessConfirmed, practiceExamCompleted: r.practiceExamCompleted, followUpNeeded: r.followUpNeeded, followUpDueDate: r.followUpDueDate, notes: r.notes }; }
export function studyPrepToRow(s: Record<string, unknown>) { return { id: String(s.id), examId: String(s.examId), studyMaterialsRequired: Boolean(s.studyMaterialsRequired), studyMaterialsOrdered: Boolean(s.studyMaterialsOrdered), studyMaterialsReceived: Boolean(s.studyMaterialsReceived), studyProvider: String(s.studyProvider), prepCourseStatus: String(s.prepCourseStatus), candidateReadinessConfirmed: Boolean(s.candidateReadinessConfirmed), practiceExamCompleted: Boolean(s.practiceExamCompleted), followUpNeeded: Boolean(s.followUpNeeded), followUpDueDate: s.followUpDueDate as string | null, notes: String(s.notes) }; }
export function rowToTask(r: typeof tasksTable.$inferSelect) { return { id: r.id, relatedType: r.relatedType, relatedId: r.relatedId, title: r.title, type: r.type, owner: r.owner, dueDate: r.dueDate, priority: r.priority, status: r.status, notes: r.notes, createdAt: r.createdAt, updatedAt: r.updatedAt }; }
export function taskToRow(t: Record<string, unknown>) { return { id: String(t.id), relatedType: String(t.relatedType), relatedId: String(t.relatedId), title: String(t.title), type: String(t.type), owner: String(t.owner), dueDate: t.dueDate as string | null, priority: String(t.priority), status: String(t.status), notes: String(t.notes), createdAt: String(t.createdAt), updatedAt: String(t.updatedAt) }; }
export function rowToEscalation(r: typeof escalationsTable.$inferSelect) { return { id: r.id, examId: r.examId, reason: r.reason, severity: r.severity, owner: r.owner, dueDate: r.dueDate, decisionNeeded: r.decisionNeeded, clientFacingRisk: r.clientFacingRisk, applicationBlockingRisk: r.applicationBlockingRisk, boardFacingRisk: r.boardFacingRisk, status: r.status, notes: r.notes, createdAt: r.createdAt, updatedAt: r.updatedAt }; }
export function escalationToRow(e: Record<string, unknown>) { return { id: String(e.id), examId: String(e.examId), reason: String(e.reason), severity: String(e.severity), owner: String(e.owner), dueDate: e.dueDate as string | null, decisionNeeded: String(e.decisionNeeded), clientFacingRisk: String(e.clientFacingRisk), applicationBlockingRisk: String(e.applicationBlockingRisk), boardFacingRisk: String(e.boardFacingRisk), status: String(e.status), notes: String(e.notes), createdAt: String(e.createdAt), updatedAt: String(e.updatedAt) }; }
export function rowToClientUpdate(r: typeof clientUpdateDraftsTable.$inferSelect) { return { id: r.id, examId: r.examId, clientId: r.clientId, internalStatus: r.internalStatus, proposedClientStatus: r.proposedClientStatus, draftMessage: r.draftMessage, requestedBy: r.requestedBy, reviewer: r.reviewer, approvalStatus: r.approvalStatus, approvedAt: r.approvedAt, publishedPreviewAt: r.publishedPreviewAt, externalPublishId: r.externalPublishId, notes: r.notes }; }
export function clientUpdateToRow(c: Record<string, unknown>) { return { id: String(c.id), examId: String(c.examId), clientId: String(c.clientId), internalStatus: String(c.internalStatus), proposedClientStatus: String(c.proposedClientStatus), draftMessage: String(c.draftMessage), requestedBy: String(c.requestedBy), reviewer: String(c.reviewer ?? ""), approvalStatus: String(c.approvalStatus), approvedAt: c.approvedAt as string | null, publishedPreviewAt: c.publishedPreviewAt as string | null, externalPublishId: c.externalPublishId as string | null, notes: String(c.notes) }; }
